//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labo2.ServiceGenNombreChaine {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGenNombreChaine.GenererNombreEtChaineSoap")]
    public interface GenererNombreEtChaineSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Labo2.ServiceGenNombreChaine.HelloWorldResponse HelloWorld(Labo2.ServiceGenNombreChaine.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Labo2.ServiceGenNombreChaine.HelloWorldResponse> HelloWorldAsync(Labo2.ServiceGenNombreChaine.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenererEntier", ReplyAction="*")]
        int GenererEntier(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenererEntier", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GenererEntierAsync(int min, int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenererDouble", ReplyAction="*")]
        double GenererDouble(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenererDouble", ReplyAction="*")]
        System.Threading.Tasks.Task<double> GenererDoubleAsync(double a, double b);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GenererChaineResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenererChaine", ReplyAction="*")]
        Labo2.ServiceGenNombreChaine.GenererChaineResponse GenererChaine(Labo2.ServiceGenNombreChaine.GenererChaineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenererChaine", ReplyAction="*")]
        System.Threading.Tasks.Task<Labo2.ServiceGenNombreChaine.GenererChaineResponse> GenererChaineAsync(Labo2.ServiceGenNombreChaine.GenererChaineRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Labo2.ServiceGenNombreChaine.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Labo2.ServiceGenNombreChaine.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labo2.ServiceGenNombreChaine.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Labo2.ServiceGenNombreChaine.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenererChaineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenererChaine", Namespace="http://tempuri.org/", Order=0)]
        public Labo2.ServiceGenNombreChaine.GenererChaineRequestBody Body;
        
        public GenererChaineRequest() {
        }
        
        public GenererChaineRequest(Labo2.ServiceGenNombreChaine.GenererChaineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenererChaineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int longueur;
        
        public GenererChaineRequestBody() {
        }
        
        public GenererChaineRequestBody(int longueur) {
            this.longueur = longueur;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenererChaineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenererChaineResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labo2.ServiceGenNombreChaine.GenererChaineResponseBody Body;
        
        public GenererChaineResponse() {
        }
        
        public GenererChaineResponse(Labo2.ServiceGenNombreChaine.GenererChaineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenererChaineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenererChaineResult;
        
        public GenererChaineResponseBody() {
        }
        
        public GenererChaineResponseBody(string GenererChaineResult) {
            this.GenererChaineResult = GenererChaineResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GenererNombreEtChaineSoapChannel : Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenererNombreEtChaineSoapClient : System.ServiceModel.ClientBase<Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap>, Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap {
        
        public GenererNombreEtChaineSoapClient() {
        }
        
        public GenererNombreEtChaineSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenererNombreEtChaineSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenererNombreEtChaineSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenererNombreEtChaineSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labo2.ServiceGenNombreChaine.HelloWorldResponse Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap.HelloWorld(Labo2.ServiceGenNombreChaine.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Labo2.ServiceGenNombreChaine.HelloWorldRequest inValue = new Labo2.ServiceGenNombreChaine.HelloWorldRequest();
            inValue.Body = new Labo2.ServiceGenNombreChaine.HelloWorldRequestBody();
            Labo2.ServiceGenNombreChaine.HelloWorldResponse retVal = ((Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labo2.ServiceGenNombreChaine.HelloWorldResponse> Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap.HelloWorldAsync(Labo2.ServiceGenNombreChaine.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labo2.ServiceGenNombreChaine.HelloWorldResponse> HelloWorldAsync() {
            Labo2.ServiceGenNombreChaine.HelloWorldRequest inValue = new Labo2.ServiceGenNombreChaine.HelloWorldRequest();
            inValue.Body = new Labo2.ServiceGenNombreChaine.HelloWorldRequestBody();
            return ((Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int GenererEntier(int min, int max) {
            return base.Channel.GenererEntier(min, max);
        }
        
        public System.Threading.Tasks.Task<int> GenererEntierAsync(int min, int max) {
            return base.Channel.GenererEntierAsync(min, max);
        }
        
        public double GenererDouble(double a, double b) {
            return base.Channel.GenererDouble(a, b);
        }
        
        public System.Threading.Tasks.Task<double> GenererDoubleAsync(double a, double b) {
            return base.Channel.GenererDoubleAsync(a, b);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labo2.ServiceGenNombreChaine.GenererChaineResponse Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap.GenererChaine(Labo2.ServiceGenNombreChaine.GenererChaineRequest request) {
            return base.Channel.GenererChaine(request);
        }
        
        public string GenererChaine(int longueur) {
            Labo2.ServiceGenNombreChaine.GenererChaineRequest inValue = new Labo2.ServiceGenNombreChaine.GenererChaineRequest();
            inValue.Body = new Labo2.ServiceGenNombreChaine.GenererChaineRequestBody();
            inValue.Body.longueur = longueur;
            Labo2.ServiceGenNombreChaine.GenererChaineResponse retVal = ((Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap)(this)).GenererChaine(inValue);
            return retVal.Body.GenererChaineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labo2.ServiceGenNombreChaine.GenererChaineResponse> Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap.GenererChaineAsync(Labo2.ServiceGenNombreChaine.GenererChaineRequest request) {
            return base.Channel.GenererChaineAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labo2.ServiceGenNombreChaine.GenererChaineResponse> GenererChaineAsync(int longueur) {
            Labo2.ServiceGenNombreChaine.GenererChaineRequest inValue = new Labo2.ServiceGenNombreChaine.GenererChaineRequest();
            inValue.Body = new Labo2.ServiceGenNombreChaine.GenererChaineRequestBody();
            inValue.Body.longueur = longueur;
            return ((Labo2.ServiceGenNombreChaine.GenererNombreEtChaineSoap)(this)).GenererChaineAsync(inValue);
        }
    }
}
