import {SuperHero} from "../pckgClases/SuperHero";
import {Livres} from "../pckgClases/Livres";

export const listeSuperHero = [
    new SuperHero(1, "Clark", "Kent", "Superman", "Metropolis"),
    new SuperHero(2, "Bruce", "Wayne", "Batman", "Gotham"),
    new SuperHero(3, "Peter", "Parker", "Spiderman", "New York"),
    new SuperHero(4, "Diana", "Prince", "Wonder Woman", "Themyscira"),
    new SuperHero(5, "Barry", "Allen", "The Flash", "Central City"),
    new SuperHero(6, "Hal", "Jordan", "Green Lantern", "Coast City"),
    new SuperHero(7, "Arthur", "Curry", "Aquaman", "Atlantis"),
    new SuperHero(8, "Jean", "Grey", "Phoenix", "Xavier's School"),
    new SuperHero(9, "Scott", "Summers", "Cyclops", "Xavier's School"),
    new SuperHero(10, "Ororo", "Munroe", "Storm", "Xavier's School"),
    new SuperHero(11, "Logan", "Howlett", "Wolverine", "Xavier's School"),
    new SuperHero(12, "Charles", "Xavier", "Professor X", "Xavier's School"),
    new SuperHero(13, "Erik", "Lehnsherr", "Magneto", "Genosha"),
    new SuperHero(14, "Natasha", "Romanoff", "Black Widow", "Russia"),
    new SuperHero(15, "Tony", "Stark", "Iron Man", "New York"),
    new SuperHero(16, "Steve", "Rogers", "Captain America", "Washington"),
    new SuperHero(17, "Hank", "Pym", "Ant-Man", "New York"),
    new SuperHero(18, "Janet", "Van Dyne", "Wasp", "New York"),
    new SuperHero(19, "T'Challa", "Black Panther", "Black Panther", "Wakanda"),
    new SuperHero(20, "Vision", "Vision", "Vision", "Avengers"),
    new SuperHero(21, "Thor", "Odinson", "Thor", "Asgard"),
    new SuperHero(22, "Kate", "Bishop", "Hawkeye", "New York"),
    new SuperHero(23, "Carol", "Danvers", "Captain Marvel", "Boston"),
    new SuperHero(24, "Kamala", "Khan", "Ms. Marvel", "Jersey City"),
    new SuperHero(25, "Jennifer", "Walters", "She-Hulk", "Los Angeles"),
    new SuperHero(26, "Peter", "Quill", "Star-Lord", "Missouri")
];

export const livres = [
    new Livres(1, "Alexandre Dumas", "Les 3 mousquetaires", "Roman historique en feuilletons", "Le Siècle", "1844-03-01"),
    new Livres(2, "Victor Hugo", "Les misérables", "Roman", "Albert Lacroix et Cie.", "1862-01-01"),
    new Livres(3, "Albert Camus", "L'étranger", "Roman", "Éditions Gallimard", "1942-05-19"),
    new Livres(4, "Michel Tremblay", "Les belles-soeurs", "Comédie dramatique", "Leméac", "1968-08-28"),
    new Livres(5, "Gabrielle Roy", "Bonheur d'occasion", "Roman", "Pascal", "1947-12-01"),
    new Livres(6, "Alice Peterson", "capsicin pleiotropism", "pragmarize", "rariety", "2000-03-26"),
    new Livres(7, "John Price", "outfigured whiskerless", "scapulothoracic", "tomosis", "2020-05-07"),
    new Livres(8, "Judith Ward", "scrofulaweed prefabricated", "aerostatic", "oligocholia", "1918-08-27"),
    new Livres(9, "Charles Lewis", "hotels noil", "unmonopolized", "unrotary", "1904-09-11"),
    new Livres(10, "Lowell Archer", "chilly preinvestigation", "unmetamorphic", "origenist", "2005-12-24"),
    new Livres(11, "Jeremy Lat", "silverly fancies", "ostealgia", "soign", "2002-11-05"),
    new Livres(12, "Holly Boykin", "asterozoa dominion", "supercharge", "nonhistrionical", "1902-05-24"),
    new Livres(13, "Sally Loughmiller", "pauciarticulate armament", "oryzorictes", "syllogistics", "1903-08-26"),
    new Livres(14, "Chantelle Becker", "distraught carrack", "disobliger", "accable", "1930-06-13"),
    new Livres(15, "Clarence Garcia", "aphroditeum bribers", "chippiest", "physicking", "1999-02-02"),
    new Livres(16, "Alexis Huland", "nautiform indorsees", "jack", "preaccused", "1941-03-06"),
    new Livres(17, "Irene Radaker", "seventeenths galbe", "partialising", "algivorous", "1981-03-02"),
    new Livres(18, "Dorothy Jones", "preornamental readaptive", "melampyrin", "bandless", "1956-08-17"),
    new Livres(19, "Eric Hutchinson", "dysaptation fyrdung", "libertine", "trecentist", "1921-02-15"),
    new Livres(20, "Anthony Smith", "stonegale balebos", "tannogallate", "breechloader", "1989-04-04"),
    new Livres(21, "Mary Carson", "album lodge", "prole", "hick", "1989-06-23"),
    new Livres(22, "Thomas Skidmore", "calamars unphilological", "coptine", "bakwiri", "2021-07-13"),
    new Livres(23, "Ellen Boyer", "eosinophilia teleosteous", "dactyliographic", "psammous", "1959-11-23"),
    new Livres(24, "Ronald Williams", "zircofluoride urocystitis", "constipating", "mylodei", "1993-08-24"),
    new Livres(25, "Charles Stephens", "gabfest contrafissure", "yammerers", "exquire", "1913-02-25")
];